import Mathlib
import OPHProofChain.Hypercharge

/-!
# The ℤ₆ kernel of the Standard-Model center action (L2.4, algebra half 2)

Machine-checks the compact paper's **Proposition [Global quotient from the
realized matter spectrum]**
(`observer-patch-holography/paper/recovering_relativity_and_standard_model_structure_from_observer_overlap_consistency_compact.tex:5753–5775`):
the subgroup of the center of `SU(3)×SU(2)×U(1)` acting trivially on every
realized Standard-Model multiplet is **exactly ℤ₆**, generated by
`g₀ = (ω₃, −1, e^{iπ/3})`.

## Model

The center is `ℤ₃ × ℤ₂ × U(1)`. Written additively, an element is
`(a, b, θ) : ZMod 3 × ZMod 2 × AddCircle (1:ℝ)`, and it acts on a multiplet
of triality `t`, `SU(2)`-duality `d`, and integer charge `q := 6Y` by the
circle phase

```
phase (a,b,θ) (t,d,q) = t•(a/3) + d•(b/2) + q•θ   ∈ ℝ/ℤ.
```

The six realized multiplets (per generation, plus Higgs) carry, in the
hypercharge normalization proved forced in `Hypercharge.lean`,

```
Q = (1, 1, 1)    u^c = (2, 0, −4)    d^c = (2, 0, 2)
L = (0, 1, −3)   e^c = (0, 0, 6)     H = (0, 1, 3)
```

(the bridge lemma `charges_match_hypercharges` checks `q = 6Y` against
`Hypercharge.smAssignment` by evaluation).

## Results

* `g0k_actsTrivially` — every `g0k k = (k mod 3, k mod 2, k/6)`, `k : ℤ`,
  acts trivially on all six multiplets: the paper's six phase checks
  `2t + 3d + q ≡ 0 (mod 6)`, machine-checked.
* `actsTrivially_iff` — **the converse**: a central element acts trivially
  on all six multiplets **iff** it is some `g0k k`. Exactly as in the
  paper, two multiplets suffice for the forward direction: `e^c` pins the
  `U(1)` part to a sixth root of unity, `Q` then pins the `ℤ₃ × ℤ₂` part.
* `g0k_eq_iff` — `g0k k = g0k k' ↔ k ≡ k' (mod 6)`.
* `kernel_bijection` / `kernelEquivZMod6` — the trivially-acting subgroup
  is in bijection with `ZMod 6`: **the kernel is exactly ℤ₆**, so the
  faithfully-acting gauge group is `SU(3)×SU(2)×U(1)/ℤ₆`.
* `addOrderOf_g0` — the paper's generator `g₀ = g0k 1` has additive order
  exactly 6.

## Honest scope

This is the **algebra half** of proof-chain link L2.4. It does *not*
provide: the selection of the matter package and of `N_c = 3` — in the OPH
chain that is **MAR** (compact paper Axiom `ax:mar`), the named physical
hypothesis — and it does not derive the gauge group. Together with
`Hypercharge.lean`: *given* the realized package, the hypercharge lattice
is forced (anomalies + Yukawa closure) and the global structure is forced
to the ℤ₆ quotient — both machine-checked; MAR stays open physics.

No `sorry`, no new axioms, no `native_decide`.
-/

namespace OPHProofChain.CenterZ6

/-- The circle group `ℝ/ℤ`, the additive model of `U(1)`. -/
abbrev Circle : Type := AddCircle (1 : ℝ)

/-- The center of `SU(3)×SU(2)×U(1)`, additively:
    `ℤ₃ × ℤ₂ × U(1) = ZMod 3 × ZMod 2 × ℝ/ℤ`. -/
abbrev CenterSM : Type := ZMod 3 × ZMod 2 × Circle

/-- A multiplet's center data: `SU(3)` triality `t`, `SU(2)` duality `d`
    (0 for singlets, 1 for doublets), and integer hypercharge `q = 6Y`. -/
structure Rep where
  /-- triality (0 for `1`, 1 for `3`, 2 for `3̄`) -/
  t : ℕ
  /-- duality (0 for `SU(2)` singlet, 1 for doublet) -/
  d : ℕ
  /-- `q := 6Y ∈ ℤ` -/
  q : ℤ

/-- The `ℤ₃` phase contribution `a/3 ∈ ℝ/ℤ`. -/
noncomputable def z3 (a : ZMod 3) : Circle := ((a.val : ℝ) / 3 : ℝ)

/-- The `ℤ₂` phase contribution `b/2 ∈ ℝ/ℤ`. -/
noncomputable def z2 (b : ZMod 2) : Circle := ((b.val : ℝ) / 2 : ℝ)

/-- The phase by which the central element `g` acts on the multiplet `r`. -/
noncomputable def phase (g : CenterSM) (r : Rep) : Circle :=
  r.t • z3 g.1 + r.d • z2 g.2.1 + r.q • g.2.2

/-- quark doublet `Q = (3,2)_{1/6}` -/
def repQ : Rep := ⟨1, 1, 1⟩
/-- up singlet `u^c = (3̄,1)_{−2/3}` -/
def repU : Rep := ⟨2, 0, -4⟩
/-- down singlet `d^c = (3̄,1)_{1/3}` -/
def repD : Rep := ⟨2, 0, 2⟩
/-- lepton doublet `L = (1,2)_{−1/2}` -/
def repL : Rep := ⟨0, 1, -3⟩
/-- charged-lepton singlet `e^c = (1,1)_{1}` -/
def repE : Rep := ⟨0, 0, 6⟩
/-- Higgs doublet `H = (1,2)_{1/2}` -/
def repH : Rep := ⟨0, 1, 3⟩

/-- The charges `q` of the six multiplets are exactly `6Y` for the
    hypercharge lattice forced in `Hypercharge.lean` — the two modules
    describe one package. -/
theorem charges_match_hypercharges :
    (repQ.q : ℚ) = 6 * Hypercharge.smAssignment.YQ ∧
    (repU.q : ℚ) = 6 * Hypercharge.smAssignment.Yu ∧
    (repD.q : ℚ) = 6 * Hypercharge.smAssignment.Yd ∧
    (repL.q : ℚ) = 6 * Hypercharge.smAssignment.YL ∧
    (repE.q : ℚ) = 6 * Hypercharge.smAssignment.Ye ∧
    (repH.q : ℚ) = 6 * Hypercharge.smAssignment.YH := by
  norm_num [repQ, repU, repD, repL, repE, repH, Hypercharge.smAssignment]

/-- The center element acts trivially on the whole realized package. -/
def ActsTrivially (g : CenterSM) : Prop :=
  phase g repQ = 0 ∧ phase g repU = 0 ∧ phase g repD = 0 ∧
    phase g repL = 0 ∧ phase g repE = 0 ∧ phase g repH = 0

/-- The candidate kernel elements: `g0k k = (k mod 3, k mod 2, k/6)`.
    `g0k 1` is the paper's generator `g₀ = (ω₃, −1, e^{iπ/3})`. -/
noncomputable def g0k (k : ℤ) : CenterSM :=
  ((k : ZMod 3), (k : ZMod 2), (((k : ℝ) / 6 : ℝ) : Circle))

/-- The paper's generator `g₀`. -/
noncomputable def g0 : CenterSM := g0k 1

/-! ### Circle-arithmetic toolbox -/

/-- The quotient map `ℝ →+ ℝ/ℤ`, definitionally the coercion. -/
noncomputable def mkHom : ℝ →+ Circle :=
  QuotientAddGroup.mk' (AddSubgroup.zmultiples (1 : ℝ))

theorem coe_smul_int (n : ℤ) (x : ℝ) :
    n • ((x : ℝ) : Circle) = (((n : ℝ) * x : ℝ) : Circle) := by
  have h : mkHom (n • x) = n • mkHom x := map_zsmul mkHom n x
  have h' : (((n • x : ℝ)) : Circle) = n • ((x : ℝ) : Circle) := h
  rw [← h']
  norm_num [zsmul_eq_mul]

theorem coe_smul_nat (n : ℕ) (x : ℝ) :
    n • ((x : ℝ) : Circle) = (((n : ℝ) * x : ℝ) : Circle) := by
  have h : mkHom (n • x) = n • mkHom x := map_nsmul mkHom n x
  have h' : (((n • x : ℝ)) : Circle) = n • ((x : ℝ) : Circle) := h
  rw [← h']
  norm_num [nsmul_eq_mul]

theorem coe_add' (x y : ℝ) :
    ((x : ℝ) : Circle) + ((y : ℝ) : Circle) = (((x + y : ℝ)) : Circle) :=
  (map_add mkHom x y).symm

/-- Two reals are circle-equal iff they differ by an integer. -/
theorem coe_eq_coe_iff {x y : ℝ} :
    ((x : ℝ) : Circle) = ((y : ℝ) : Circle) ↔ ∃ m : ℤ, x - y = m := by
  constructor
  · intro h
    have hsub : (((x - y : ℝ)) : Circle) = ((x : ℝ) : Circle) - ((y : ℝ) : Circle) :=
      map_sub mkHom x y
    rw [h, sub_self] at hsub
    rw [AddCircle.coe_eq_zero_iff] at hsub
    obtain ⟨m, hm⟩ := hsub
    refine ⟨m, ?_⟩
    have : (m : ℝ) • (1 : ℝ) = (m : ℝ) := by rw [smul_eq_mul, mul_one]
    rw [zsmul_eq_mul, mul_one] at hm
    linarith [hm]
  · rintro ⟨m, hm⟩
    have hx : x = y + (m : ℝ) := by linarith
    rw [hx, ← coe_add']
    have hz : (((m : ℝ)) : Circle) = 0 := by
      rw [AddCircle.coe_eq_zero_iff]
      exact ⟨m, by rw [zsmul_eq_mul, mul_one]⟩
    rw [hz, add_zero]

/-- A real equal to an integer is zero on the circle. -/
theorem coe_eq_zero_of_int (x : ℝ) (m : ℤ) (h : x = m) :
    ((x : ℝ) : Circle) = 0 := by
  rw [AddCircle.coe_eq_zero_iff]
  exact ⟨m, by rw [zsmul_eq_mul, mul_one, h]⟩

/-! ### Every `g0k k` acts trivially -/

/-- The generic phase computation on `g0k k`: if the multiplet's
    `2t + 3d + q` equals `6c`, the phase is the integer
    `k·c + t·m₃ + d·m₂` (the `m`'s absorbing the `val` representatives),
    i.e. `0` on the circle. This is the paper's phase check
    `ω₃^t·(−1)^d·η^q = 1` in additive form. -/
theorem g0k_phase_eq_zero (k : ℤ) (r : Rep) (c : ℤ)
    (hc : 2 * (r.t : ℤ) + 3 * (r.d : ℤ) + r.q = 6 * c) :
    phase (g0k k) r = 0 := by
  unfold phase g0k z3 z2
  -- the `val` representatives differ from `k` by integer multiples
  have hval3 : ∃ m : ℤ, (((k : ZMod 3).val : ℝ)) = (k : ℝ) + 3 * m := by
    refine ⟨-(k / 3), ?_⟩
    have h : (((k : ZMod 3).val : ℤ) : ℝ) = ((k % 3 : ℤ) : ℝ) := by
      exact_mod_cast congrArg (fun z : ℤ => (z : ℝ)) (ZMod.val_intCast (n := 3) k)
    have hmod : (k % 3 : ℤ) = k - 3 * (k / 3) := Int.emod_def k 3
    push_cast at h ⊢
    rw [h]
    push_cast [hmod]
    ring
  have hval2 : ∃ m : ℤ, (((k : ZMod 2).val : ℝ)) = (k : ℝ) + 2 * m := by
    refine ⟨-(k / 2), ?_⟩
    have h : (((k : ZMod 2).val : ℤ) : ℝ) = ((k % 2 : ℤ) : ℝ) := by
      exact_mod_cast congrArg (fun z : ℤ => (z : ℝ)) (ZMod.val_intCast (n := 2) k)
    have hmod : (k % 2 : ℤ) = k - 2 * (k / 2) := Int.emod_def k 2
    push_cast at h ⊢
    rw [h]
    push_cast [hmod]
    ring
  obtain ⟨m3, hm3⟩ := hval3
  obtain ⟨m2, hm2⟩ := hval2
  rw [coe_smul_nat, coe_smul_nat, coe_smul_int, coe_add', coe_add']
  have hcR : 2 * (r.t : ℝ) + 3 * (r.d : ℝ) + (r.q : ℝ) = 6 * (c : ℝ) := by
    exact_mod_cast congrArg (fun z : ℤ => (z : ℝ)) hc
  apply coe_eq_zero_of_int _ (k * c + (r.t : ℤ) * m3 + (r.d : ℤ) * m2)
  rw [hm3, hm2]
  push_cast
  linear_combination ((k : ℝ) / 6) * hcR

/-- **Sufficiency** (the paper's six checks): every `g0k k` acts trivially
    on the whole realized Standard-Model package. -/
theorem g0k_actsTrivially (k : ℤ) : ActsTrivially (g0k k) := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
  · exact g0k_phase_eq_zero k repQ 1 (by norm_num [repQ])
  · exact g0k_phase_eq_zero k repU 0 (by norm_num [repU])
  · exact g0k_phase_eq_zero k repD 1 (by norm_num [repD])
  · exact g0k_phase_eq_zero k repL 0 (by norm_num [repL])
  · exact g0k_phase_eq_zero k repE 1 (by norm_num [repE])
  · exact g0k_phase_eq_zero k repH 1 (by norm_num [repH])

/-! ### Necessity: nothing else acts trivially -/

/-- **The kernel characterization** (compact paper, Proposition `prop:z6`):
    a central element acts trivially on the realized package **iff** it is
    `g0k k` for some integer `k`. The forward direction uses only the two
    multiplets the paper uses: `e^c` (pins the `U(1)` part to a sixth root
    of unity) and `Q` (then pins the `ℤ₃ × ℤ₂` part). -/
theorem actsTrivially_iff (g : CenterSM) :
    ActsTrivially g ↔ ∃ k : ℤ, g = g0k k := by
  constructor
  · rintro ⟨hQ, -, -, -, hE, -⟩
    obtain ⟨a, b, θ⟩ := g
    obtain ⟨x, rfl⟩ : ∃ x : ℝ, ((x : ℝ) : Circle) = θ := Quotient.exists_rep θ
    -- `e^c`: 6θ = 0 forces θ = n/6
    have hE6 : (((6 * x : ℝ)) : Circle) = (((0 : ℝ)) : Circle) := by
      have h1 : phase (a, b, ((x : ℝ) : Circle)) repE = (6 : ℤ) • ((x : ℝ) : Circle) := by
        unfold phase repE z3 z2
        simp
      have h2 := hE
      rw [h1, coe_smul_int] at h2
      push_cast at h2
      rw [h2]
      rfl
    rw [coe_eq_coe_iff] at hE6
    obtain ⟨n, hn⟩ := hE6
    have hx : x = (n : ℝ) / 6 := by linarith
    -- `Q`: a/3 + b/2 + θ = 0 forces 2A + 3B + n = 6m
    have hQ0 : (((a.val : ℝ) / 3 + ((b.val : ℝ) / 2 + x) : ℝ) : Circle)
        = (((0 : ℝ)) : Circle) := by
      have h1 : phase (a, b, ((x : ℝ) : Circle)) repQ
          = (((a.val : ℝ) / 3 + ((b.val : ℝ) / 2 + x) : ℝ) : Circle) := by
        unfold phase repQ z3 z2
        simp only [one_smul]
        rw [coe_add', coe_add']
        ring_nf
      rw [← h1, hQ]
      rfl
    rw [coe_eq_coe_iff] at hQ0
    obtain ⟨m, hm⟩ := hQ0
    have hkey : 2 * (a.val : ℤ) + 3 * (b.val : ℤ) + n = 6 * m := by
      have hR : 2 * (a.val : ℝ) + 3 * (b.val : ℝ) + (n : ℝ) = 6 * (m : ℝ) := by
        rw [hx] at hm
        linarith
      exact_mod_cast hR
    refine ⟨n, ?_⟩
    unfold g0k
    have hcomp1 : a = ((n : ℤ) : ZMod 3) := by
      have hdvd : (3 : ℤ) ∣ n - (a.val : ℤ) :=
        ⟨2 * m - (a.val : ℤ) - (b.val : ℤ), by linarith⟩
      have hmodeq : ((a.val : ℤ) : ZMod 3) = ((n : ℤ) : ZMod 3) := by
        rw [ZMod.intCast_eq_intCast_iff]
        exact Int.modEq_iff_dvd.mpr (by push_cast; exact hdvd)
      rw [← hmodeq]
      push_cast
      exact (ZMod.natCast_rightInverse a).symm
    have hcomp2 : b = ((n : ℤ) : ZMod 2) := by
      have hdvd : (2 : ℤ) ∣ n - (b.val : ℤ) :=
        ⟨3 * m - (a.val : ℤ) - 2 * (b.val : ℤ), by linarith⟩
      have hmodeq : ((b.val : ℤ) : ZMod 2) = ((n : ℤ) : ZMod 2) := by
        rw [ZMod.intCast_eq_intCast_iff]
        exact Int.modEq_iff_dvd.mpr (by push_cast; exact hdvd)
      rw [← hmodeq]
      push_cast
      exact (ZMod.natCast_rightInverse b).symm
    refine Prod.ext hcomp1 (Prod.ext hcomp2 ?_)
    show ((x : ℝ) : Circle) = (((n : ℝ) / 6 : ℝ) : Circle)
    rw [hx]
  · rintro ⟨k, rfl⟩
    exact g0k_actsTrivially k

/-- The parameterization `g0k` factors through `ZMod 6` faithfully:
    `g0k k = g0k k' ↔ k ≡ k' (mod 6)`. (The circle component alone decides
    the forward direction.) -/
theorem g0k_eq_iff (k k' : ℤ) : g0k k = g0k k' ↔ (k : ZMod 6) = (k' : ZMod 6) := by
  constructor
  · intro h
    have hθ : (((k : ℝ) / 6 : ℝ) : Circle) = (((k' : ℝ) / 6 : ℝ) : Circle) :=
      congrArg (fun g : CenterSM => g.2.2) h
    rw [coe_eq_coe_iff] at hθ
    obtain ⟨m, hm⟩ := hθ
    have h6 : k - k' = 6 * m := by
      have hR : (k : ℝ) - (k' : ℝ) = 6 * (m : ℝ) := by linarith
      exact_mod_cast hR
    rw [ZMod.intCast_eq_intCast_iff]
    exact Int.modEq_iff_dvd.mpr ⟨-m, by push_cast; linarith⟩
  · intro h
    have hmodeq : k ≡ k' [ZMOD (6 : ℕ)] := (ZMod.intCast_eq_intCast_iff _ _ _).mp h
    have h6 : (6 : ℤ) ∣ k' - k := Int.ModEq.dvd hmodeq
    obtain ⟨c, hc⟩ := h6
    unfold g0k
    have hmod3 : (k : ZMod 3) = (k' : ZMod 3) := by
      rw [ZMod.intCast_eq_intCast_iff]
      exact hmodeq.of_dvd (by norm_num)
    have hmod2 : (k : ZMod 2) = (k' : ZMod 2) := by
      rw [ZMod.intCast_eq_intCast_iff]
      exact hmodeq.of_dvd (by norm_num)
    refine Prod.ext hmod3 (Prod.ext hmod2 ?_)
    show (((k : ℝ) / 6 : ℝ) : Circle) = (((k' : ℝ) / 6 : ℝ) : Circle)
    rw [coe_eq_coe_iff]
    refine ⟨-c, ?_⟩
    have : (k' : ℝ) - (k : ℝ) = 6 * (c : ℝ) := by exact_mod_cast hc
    push_cast
    linarith

/-- **The kernel is exactly ℤ₆**: an explicit bijection from `ZMod 6` onto
    the trivially-acting central elements. -/
theorem kernel_bijection :
    ∃ f : ZMod 6 → {g : CenterSM // ActsTrivially g}, Function.Bijective f := by
  refine ⟨fun k => ⟨g0k (k.val : ℤ), g0k_actsTrivially _⟩, ?_, ?_⟩
  · intro k k' h
    have h1 := (g0k_eq_iff (k.val : ℤ) (k'.val : ℤ)).mp (congrArg Subtype.val h)
    have hk : ((k.val : ℤ) : ZMod 6) = k := by
      push_cast
      exact ZMod.natCast_rightInverse k
    have hk' : ((k'.val : ℤ) : ZMod 6) = k' := by
      push_cast
      exact ZMod.natCast_rightInverse k'
    rw [hk, hk'] at h1
    exact h1
  · rintro ⟨g, hg⟩
    obtain ⟨k, rfl⟩ := (actsTrivially_iff g).mp hg
    refine ⟨(k : ZMod 6), ?_⟩
    apply Subtype.ext
    show g0k ((((k : ZMod 6)).val : ℤ)) = g0k k
    rw [g0k_eq_iff]
    push_cast
    exact congrArg Nat.cast (rfl : ((k : ZMod 6)).val = ((k : ZMod 6)).val) |>.trans
      (ZMod.natCast_rightInverse (k : ZMod 6))

/-- The trivially-acting subgroup, as an equivalence with `ZMod 6`. -/
noncomputable def kernelEquivZMod6 : ZMod 6 ≃ {g : CenterSM // ActsTrivially g} :=
  Equiv.ofBijective _ kernel_bijection.choose_spec

/-- The generator `g₀` has additive order exactly 6 (so it generates the
    full ℤ₆ kernel). -/
theorem addOrderOf_g0 : addOrderOf g0 = 6 := by
  have hsmul : ∀ n : ℕ, n • g0 = g0k (n : ℤ) := by
    intro n
    unfold g0 g0k
    have h1 : n • ((1 : ℤ) : ZMod 3) = ((n : ℤ) : ZMod 3) := by
      push_cast
      rw [nsmul_eq_mul, mul_one]
    have h2 : n • ((1 : ℤ) : ZMod 2) = ((n : ℤ) : ZMod 2) := by
      push_cast
      rw [nsmul_eq_mul, mul_one]
    have h3 : n • ((((1 : ℤ) : ℝ) / 6 : ℝ) : Circle) = ((((n : ℤ) : ℝ) / 6 : ℝ) : Circle) := by
      rw [coe_smul_nat]
      push_cast
      ring_nf
    calc n • (((1 : ℤ) : ZMod 3), ((1 : ℤ) : ZMod 2), ((((1 : ℤ) : ℝ) / 6 : ℝ) : Circle))
        = (n • ((1 : ℤ) : ZMod 3), n • ((1 : ℤ) : ZMod 2),
            n • ((((1 : ℤ) : ℝ) / 6 : ℝ) : Circle)) := rfl
      _ = (((n : ℤ) : ZMod 3), ((n : ℤ) : ZMod 2), ((((n : ℤ) : ℝ) / 6 : ℝ) : Circle)) := by
          rw [h1, h2, h3]
  have hzero : g0k 0 = 0 := by
    unfold g0k
    refine Prod.ext ?_ (Prod.ext ?_ ?_)
    · norm_num
    · norm_num
    · show ((((0 : ℤ) : ℝ) / 6 : ℝ) : Circle) = 0
      apply coe_eq_zero_of_int _ 0
      norm_num
  rw [addOrderOf_eq_iff (by norm_num)]
  constructor
  · rw [hsmul 6, show ((6 : ℕ) : ℤ) = 6 from rfl,
      (g0k_eq_iff 6 0).mpr (by decide), hzero]
  · intro m hm hm0 hcontra
    rw [hsmul m, ← hzero] at hcontra
    have h1 := (g0k_eq_iff (m : ℤ) 0).mp hcontra
    have h6 : (6 : ℤ) ∣ (m : ℤ) := by
      have h' : ((m : ℤ) : ZMod 6) = 0 := by simpa using h1
      exact (ZMod.intCast_zmod_eq_zero_iff_dvd _ 6).mp h'
    have h6' : (6 : ℕ) ∣ m := by exact_mod_cast h6
    have := Nat.le_of_dvd hm0 h6'
    omega

/-! ### `[formal-v7]` The kernel as a GROUP isomorphism (holes-audit F10c)

The audit observed that the tree proved a *set bijection* of the kernel with
`ZMod 6` (plus `addOrderOf g0 = 6`) while the chain documents said "the
kernel is exactly ℤ₆" — a group statement. Here the group form is assembled:
the trivially-acting elements form an additive subgroup, and it is
isomorphic to `ZMod 6` **as an additive group**. -/

/-- `g0k` is additive: `g0k (k + k') = g0k k + g0k k'`. -/
theorem g0k_add (k k' : ℤ) : g0k (k + k') = g0k k + g0k k' := by
  unfold g0k
  refine Prod.ext ?_ (Prod.ext ?_ ?_)
  · push_cast
    rfl
  · push_cast
    rfl
  · show (((((k + k' : ℤ)) : ℝ) / 6 : ℝ) : Circle) = _
    rw [show (((k + k' : ℤ) : ℝ) / 6 : ℝ)
        = ((k : ℝ) / 6) + ((k' : ℝ) / 6) from by push_cast; ring,
      ← coe_add']
    rfl

/-- The phase map is additive in the central element. -/
theorem phase_add (g h : CenterSM) (r : Rep) :
    phase (g + h) r = phase g r + phase h r := by
  unfold phase
  have hz3 : z3 (g.1 + h.1) = z3 g.1 + z3 h.1 := by
    unfold z3
    rw [coe_add', coe_eq_coe_iff]
    obtain ⟨k, hk⟩ : ∃ k : ℕ, g.1.val + h.1.val = (g.1 + h.1).val + 3 * k := by
      have hmod : (g.1 + h.1).val = (g.1.val + h.1.val) % 3 :=
        ZMod.val_add g.1 h.1
      exact ⟨(g.1.val + h.1.val) / 3, by omega⟩
    refine ⟨-(k : ℤ), ?_⟩
    have hkR : (g.1.val : ℝ) + (h.1.val : ℝ)
        = ((g.1 + h.1).val : ℝ) + 3 * (k : ℝ) := by exact_mod_cast hk
    push_cast
    linarith
  have hz2 : z2 (g.2.1 + h.2.1) = z2 g.2.1 + z2 h.2.1 := by
    unfold z2
    rw [coe_add', coe_eq_coe_iff]
    obtain ⟨k, hk⟩ : ∃ k : ℕ,
        g.2.1.val + h.2.1.val = (g.2.1 + h.2.1).val + 2 * k := by
      have hmod : (g.2.1 + h.2.1).val = (g.2.1.val + h.2.1.val) % 2 :=
        ZMod.val_add g.2.1 h.2.1
      exact ⟨(g.2.1.val + h.2.1.val) / 2, by omega⟩
    refine ⟨-(k : ℤ), ?_⟩
    have hkR : (g.2.1.val : ℝ) + (h.2.1.val : ℝ)
        = ((g.2.1 + h.2.1).val : ℝ) + 2 * (k : ℝ) := by exact_mod_cast hk
    push_cast
    linarith
  show r.t • z3 (g.1 + h.1) + r.d • z2 (g.2.1 + h.2.1) + r.q • (g.2.2 + h.2.2)
    = _
  rw [hz3, hz2, smul_add, smul_add, smul_add]
  abel

/-- The phase of the zero element vanishes. -/
theorem phase_zero (r : Rep) : phase 0 r = 0 := by
  unfold phase
  have hz3 : z3 (0 : ZMod 3) = 0 := by
    unfold z3
    apply coe_eq_zero_of_int _ 0
    norm_num
  have hz2 : z2 (0 : ZMod 2) = 0 := by
    unfold z2
    apply coe_eq_zero_of_int _ 0
    norm_num
  show r.t • z3 (0 : ZMod 3) + r.d • z2 (0 : ZMod 2) + r.q • (0 : Circle) = 0
  rw [hz3, hz2, smul_zero, smul_zero, smul_zero, add_zero, add_zero]

/-- The phase map is odd in the central element (from additivity). -/
theorem phase_neg (g : CenterSM) (r : Rep) : phase (-g) r = -phase g r := by
  have h := phase_add (-g) g r
  rw [neg_add_cancel, phase_zero] at h
  exact eq_neg_of_add_eq_zero_left h.symm

/-- **The trivially-acting central elements form an additive subgroup.** -/
noncomputable def kernelSubgroup : AddSubgroup CenterSM where
  carrier := {g | ActsTrivially g}
  add_mem' := by
    rintro g h ⟨hg1, hg2, hg3, hg4, hg5, hg6⟩ ⟨hh1, hh2, hh3, hh4, hh5, hh6⟩
    refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
      rw [phase_add] <;> simp_all
  zero_mem' := ⟨phase_zero _, phase_zero _, phase_zero _, phase_zero _,
    phase_zero _, phase_zero _⟩
  neg_mem' := by
    rintro g ⟨hg1, hg2, hg3, hg4, hg5, hg6⟩
    refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
      rw [phase_neg] <;> simp_all

/-- **`[formal-v7]` THE KERNEL IS ℤ₆ AS A GROUP (T13 addendum; audit F10c).**
    The additive-group isomorphism `ZMod 6 ≃+ ker` — upgrading the set
    bijection `kernel_bijection` and the order computation `addOrderOf_g0`
    to the group statement the chain documents quote. -/
noncomputable def kernelAddEquiv : ZMod 6 ≃+ kernelSubgroup := by
  refine AddEquiv.mk' (Equiv.ofBijective
    (fun k => (⟨g0k (k.val : ℤ), g0k_actsTrivially _⟩ : kernelSubgroup)) ⟨?_, ?_⟩) ?_
  · -- injective
    intro k k' h
    have h1 := (g0k_eq_iff (k.val : ℤ) (k'.val : ℤ)).mp
      (congrArg Subtype.val h)
    have hk : ((k.val : ℤ) : ZMod 6) = k := by
      push_cast
      exact ZMod.natCast_rightInverse k
    have hk' : ((k'.val : ℤ) : ZMod 6) = k' := by
      push_cast
      exact ZMod.natCast_rightInverse k'
    rw [hk, hk'] at h1
    exact h1
  · -- surjective
    rintro ⟨g, hg⟩
    obtain ⟨k, rfl⟩ := (actsTrivially_iff g).mp hg
    refine ⟨(k : ZMod 6), ?_⟩
    apply Subtype.ext
    show g0k ((((k : ZMod 6)).val : ℤ)) = g0k k
    rw [g0k_eq_iff]
    push_cast
    exact ZMod.natCast_rightInverse (k : ZMod 6)
  · -- additive
    intro a b
    apply Subtype.ext
    show g0k (((a + b).val : ℤ)) = g0k (a.val : ℤ) + g0k (b.val : ℤ)
    rw [← g0k_add, g0k_eq_iff]
    push_cast
    rw [ZMod.natCast_rightInverse (a + b), ZMod.natCast_rightInverse a,
      ZMod.natCast_rightInverse b]

/-! ### Axiom audit -/
#print axioms charges_match_hypercharges
#print axioms g0k_actsTrivially
#print axioms actsTrivially_iff
#print axioms g0k_eq_iff
#print axioms kernel_bijection
#print axioms addOrderOf_g0
#print axioms kernelAddEquiv

end OPHProofChain.CenterZ6
